### PR TITLE
Move current docs into version namespace

### PR DESCRIPTION
**Pull request by tux-rampage**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

@froschdesign Something went odd with the documentation für multiple versions introduced with #19
It is warning that an outdated documentation is viewed. It seems that the docs must be in a folder named as the version.

### CODE REVIEW

**Comment by tux-rampage** [comment]
I am not sure if relative links inside the pages would require a rewrite. Can someone have a look and advice?

**Comment by froschdesign** [comment]
@tux-rampage 
The `mkdocs.yml` looks good.

**Review by froschdesign — APPROVED** [review]
Unfortunately I can't test locally right now, but everything looks good now.

**Comment by Xerkus** [comment]
This PR is replaced by #22 that have some additional improvements.

**Pull request closed without merging**
