### PR TITLE
Drop container-interop

### PR DESCRIPTION
**Pull request by remicollet**
which is replaced by recent servicemanager

Signed-off-by: Remi Collet <remi@famillecollet.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### CODE REVIEW

**Comment by Ocramius** [comment]
@remicollet thanks, will update `composer.lock` before merging :+1:

**Comment by remicollet** [comment]
@Ocramius notice that there is a set of laminas-* which can be improved the same way

**Comment by Ocramius** [comment]
@remicollet yeah, the idea there would be that @renovatebot would take those up, but I haven't had the time to set it up organization-wide yet.

Lemme do it here first :-)

**Comment by Ocramius** [comment]
Had to expand the patch a bit: PHP_CodeSniffer was right in finding pending `Interop\Container\` references that had to be removed.

Did my best to keep everything BC compliant, by adding a conflict with earlier `laminas/laminas-servicemanager` releases (since that component is not a strict requirement for this library to be used).

**Review by Ocramius — APPROVED** [review]
:ship: thanks for spotting this, @remicollet!

**Pull request merged**
