### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
@Ocramius Do we need to fix following issues?
Screenshot 2023-10-11 at 4 46 14 PM

**Comment by glo17680** [comment]
@Ocramius Is there any update on the fixes on this PR. Can you please advise ?

**Comment by froschdesign** [comment]
@glo17680 
The listed warnings and errors must be fixed. Any help with this is welcome!

https://github.com/laminas/laminas-di/actions/runs/6546774850/job/17777929783?pr=90#step:3:350
https://github.com/laminas/laminas-di/actions/runs/6546774850/job/17777929783?pr=90#step:3:359

**Review by Ocramius — APPROVED** [review]
Thanks!

**Pull request merged**
