### PR TITLE
Apply PHP 7.4 Syntax

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Apply PHP 7.4 Syntax and Typed property for private property only to keep BC.

### CODE REVIEW

**Comment by Ocramius** [comment]
Not sure what is up with the test failures 🤔

**Comment by samsonasik** [comment]
@Ocramius should be ok now

**Comment by samsonasik** [comment]
@Ocramius All green 🎉

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @samsonasik!

**Pull request merged**
